### ISSUE TITLE
在MIUI 12.5.7 全面屏手势下，FCL有时会毫无征兆的崩溃

### ISSUE THREAD

**Issue by high20212021** [FCL-Team/FoldCraftLauncher#136]
### Launcher Version

1.1.0

### Device Information

RedMi Note 7,Android 10,arm64

### Problem Description

这种崩溃是直接崩溃，日志都不留的那种

**Comment by 8MiYile** [comment]
既然来自MIUI的问题，那请出示MIUI提供的日志吧，就是应用崩溃的时候有个生成日志的蓝色下划线按钮，

**Comment by high20212021** [comment]
在1.1.4，此bug又被我复现了
Build version: 1.1.4 
Current date: 2024-02-08 14:49:31 
Device: Xiaomi Redmi Note 7 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.fcl/com.tungsten.fcl.activity.MainActivity}: java.lang.IllegalStateException: Configuration is already loaded
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
