### ISSUE TITLE
Add Lwjgl 3.3.1

### ISSUE THREAD

**Issue by PedrixzZ** [FCL-Team/FoldCraftLauncher#171]
### Description

Add LWJGL 3.3.1 please

### Why

.

**Comment by ShirosakiMio** [comment]
now it's working. Wait for fixing some bugs

**Comment by PedrixzZ** [comment]
Is it now possible to run VulkanMod?

**Comment by ShirosakiMio** [comment]
> Is it now possible to run VulkanMod?

yes, the same as pojav

**Comment by FrostNovaHD** [comment]
> > Is it now possible to run VulkanMod?
> 
> yes, the same as pojav

still crashes mio

**Comment by ShirosakiMio** [comment]
> > > Is it now possible to run VulkanMod?
> > 
> > 
> > yes, the same as pojav
> 
> still crashes mio

if pojav is no problem, maybe the new branch will also be.

**Comment by PedrixzZ** [comment]
[01:20:38] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?]
	at ne
t.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:232) ~[1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: com.sun.jna.LastErrorException
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launc
h.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:232) ~[1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.
MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	... 2 more
I get this error when opening Minecraft with Vulkan Mod for Android

**Comment by ShirosakiMio** [comment]
> [01:20:38] [Render thread/ERROR]: Minecraft has crashed! net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?] Caused by: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?] at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?] at ne t.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at net.minecraft.client.main.Main.main(Main.java:232) ~[1.20.4.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?] ... 2 more Caused by: java.lang.ClassNotFoundException: com.sun.jna.LastErrorException at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launc h.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?] at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at net.minecraft.client.main.Main.main(Main.java:232) ~[1.20.4.jar:?] at net.fabricmc.loader.impl.game.minecraft. MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?] ... 2 more I get this error when opening Minecraft with Vulkan Mod for Android

wait for the new branch. it is not work on the main branch. the new  branch's lwjgl is the same as pojav

**Comment by FrostNovaHD** [comment]
> > > > Is it now possible to run VulkanMod?
> > > 
> > > 
> > > yes, the same as pojav
> > 
> > 
> > still crashes mio
> 
> if pojav is no problem, maybe the new branch will also be.

Well it doesnt hapen on pojav

**Comment by FrostNovaHD** [comment]
[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13883563/latest_game.log)

**Comment by ShirosakiMio** [comment]
> [latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13883563/latest_game.log)

the cache dir of FCL seems not work. vulkan mod extract *.so to a wrong place. I try to place *.so to native lib, it works
![Screenshot_2024-01-10-15-13-14-662_com tungsten f](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/365219c8-9ef3-4acc-af20-3896552d6f84)

**Comment by FrostNovaHD** [comment]
> > [latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13883563/latest_game.log)
> 
> the cache dir of FCL seems not work. vulkan mod extract *.so to a wrong place. I try to place *.so to native lib, it works ![Screenshot_2024-01-10-15-13-14-662_com tungsten f](https://private-user-images.githubusercontent.com/19233890/295480672-365219c8-9ef3-4acc-af20-3896552d6f84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzczNTYsIm5iZiI6MTcxNjEzNzA1NiwicGF0aCI6Ii8xOTIzMzg5MC8yOTU0ODA2NzItMzY1MjE5YzgtOWVmMy00YWNjLWFmMjAtMzg5NjU1MmQ2Zjg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE2NDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNjM5OWI2NWRiNDI0MDlmZmM1NWU1NzFiYjIwZTFlMjY2N2M4MTk5OTc0ZTgzZjMxYmQ2Njc0YzJkYWZmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TXenBjTppNUjjV39We0gOucGHOR0qvw5YxAhlxmttno)

does it still work mio
