### ISSUE TITLE
External login AccessToken is not displayed normally after it becomes invalid.

### ISSUE THREAD

**Issue by Luochancy** [FCL-Team/FoldCraftLauncher#222]
### Launcher Version

1.1.3

### Device Information

Maybe all the equipment. My device is Redmi Note 11T Pro

### Problem Description

Since the server uses external login, I enabled it on the launcher. However, in the past few days, it has been impossible to start the game. The specific situation is that I got stuck there when I reached the "login" step.Then the interface is like a layer of dust. I exported the initiator log and found the following:
`[02:34:53] [com.tungsten.fcl.game.LauncherHelper.lambda$logIn$21/INFO] Credential has expired
com.tungsten.fclcore.auth.CredentialExpiredException: com.tungsten.fclcore.auth.yggdrasil.RemoteAuthenticationException: ForbiddenOperationException: 无效的 AccessToken，请重新登录
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilAccount.logIn(YggdrasilAccount.java:125)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount.lambda$logIn$0$com-tungsten-fclcore-auth-authlibinjector-AuthlibInjectorAccount(AuthlibInjectorAccount.java:62)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount$$ExternalSyntheticLambda3.get(Unknown Source:2)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount.inject(AuthlibInjectorAccount.java:100)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount.logIn(AuthlibInjectorAccount.java:62)
	at com.tungsten.fcl.game.LauncherHelper.lambda$logIn$21(LauncherHelper.java:302)
	at com.tungsten.fcl.game.LauncherHelper$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.tungsten.fclcore.task.Task$2.execute(Task.java:868)
	at com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$22$com-tungsten-fclcore-task-AsyncTaskExecutor(AsyncTaskExecutor.java:243)
	at com.tungsten.fclcore.task.AsyncTaskExecutor$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at com.tungsten.fclcore.util.Lang.lambda$wrap$2(Lang.java:291)
	at com.tungsten.fclcore.util.Lang$$ExternalSyntheticLambda7.run(Unknown Source:2)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.tungsten.fclcore.auth.yggdrasil.RemoteAuthenticationException: ForbiddenOperationException: 无效的 AccessToken，请重新登录
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.handleErrorMessage(YggdrasilService.java:230)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.handleAuthenticationResponse(YggdrasilService.java:208)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.refresh(YggdrasilService.java:115)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilAccount.logIn(YggdrasilAccount.java:122)
	... 18 more`
This may be caused by the failure of AccessToken, but I don't understand why the drive doesn't display related errors normally, but just grays out.
![Screenshot_2024-01-28-02-43-17-955_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/86495643/65ccaadb-62ba-420d-a97d-2c85f381a895)

**Comment by zkitefly** [comment]
![Screenshot_2024-01-28-15-47-13-84_c8a66bc90793a73](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/e5af2d25-15d3-4e4e-aeac-d77504524ea7)

我也遇到了这个问题

[fcl-exported-logs-2024-01-28T15-47-30.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14075313/fcl-exported-logs-2024-01-28T15-47-30.log)

**Comment by Luochancy** [comment]
In subsequent tests, related problems also occurred when logging in through my skin station. Same gray screen and unable to enter the game
I really hope the developers can fix this issue. The experience of using this launcher is really good, but I don’t want a small problem to affect the experience. At the same time, thank you to all developers for checking this issue!
