### ISSUE TITLE
莫名的崩溃问题

### ISSUE THREAD

**Issue by xingguangcuican6666** [FCL-Team/FoldCraftLauncher#262]
### Launcher Version

1.1.4.2

### Device Information

Huawei P20 arm64 Android 11(magisk root)

### Problem Description

下载完必要文件更新进入主界面时崩溃

### Launcher Crash Report

Build version: 1.1.4.2 
Current date: 2024-02-14 21:04:03 
Device: Unknown Phh-Treble vanilla 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tungsten.fclcore.fakefx.collections.ObservableListWrapper.get(ObservableListWrapper.java:61)
	at com.tungsten.fclcore.fakefx.beans.binding.ListExpression.get(ListExpression.java:244)
	at com.tungsten.fcl.ui.controller.ControllerUI.onCreate(ControllerUI.java:98)
	at com.tungsten.fcllibrary.component.ui.FCLCommonUI.lambda$new$0$com-tungsten-fcllibrary-component-ui-FCLCommonUI(FCLCommonUI.java:24)
	at com.tungsten.fcllibrary.component.ui.FCLCommonUI$$ExternalSyntheticLambda0.onFinish(Unknown Source:2)
	at com.tungsten.fcllibrary.component.ui.FCLBaseUI.lambda$setContentView$0$com-tungsten-fcllibrary-component-ui-FCLBaseUI(FCLBaseUI.java:43)
	at com.tungsten.fcllibrary.component.ui.FCLBaseUI$$ExternalSyntheticLambda0.onInflateFinished(Unknown Source:4)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$1.handleMessage(AsyncLayoutInflater.java:103)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Launcher Log File

[21:02:44] [com.tungsten.fcl.setting.ConfigHolder.loadGlobalConfig/INFO] Creating an empty global config
[21:02:44] [com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorDownloader.checkUpdate/INFO] Checking update of authlib-injector
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:88)
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:88)
[21:02:44] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[21:02:44] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:88)
[21:02:44] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=[], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[21:02:44] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:88)
[21:02:44] [com.tungsten.fcl.setting.Controllers.checkControllers/SEVERE] Failed to generate default controller!
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:128)
[21:02:44] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:127)

**Comment by ShirosakiMio** [comment]
祖传老毛病了
