### ISSUE TITLE
在游戏运行时尝试保存键位更改会崩溃

### ISSUE THREAD

**Issue by high20212021** [FCL-Team/FoldCraftLauncher#291]
### Launcher Version

1.1.5

### Device Information

Redmi Note 7,Android 10,arm64

### Problem Description

启动游戏后进入编辑模式，对某个按键进行更改之后确认，然后启动器立刻崩溃

### Java

Java 8

### Renderer

Holy-GL4ES

### Game Version

1.12.2

### Modifications Made to the Game

LiteLoader-1.12.2-SNAPSHOT

### Launcher Crash Report

Build version: 1.1.5 
Current date: 2024-03-02 10:30:13 
Device: Xiaomi Redmi Note 7 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'void com.tungsten.fclcore.fakefx.beans.InvalidationListener.invalidated(com.tungsten.fclcore.fakefx.beans.Observable)' on a null object reference
	at com.tungsten.fclcore.util.fakefx.ObservableHelper.lambda$invalidate$0$com-tungsten-fclcore-util-fakefx-ObservableHelper(ObservableHelper.java:59)
	at com.tungsten.fclcore.util.fakefx.ObservableHelper$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:832)
	at com.tungsten.fclcore.util.fakefx.ObservableHelper.invalidate(ObservableHelper.java:59)
	at com.tungsten.fcl.control.data.ControlButtonData.invalidate(ControlButtonData.java:140)
	at com.tungsten.fcl.control.data.ControlButtonData.$r8$lambda$H4ug6JzTrWk7HuaSvpnBZxRk2Uw(Unknown Source:0)
	at com.tungsten.fcl.control.data.ControlButtonData$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.tungsten.fcl.util.FXUtils.lambda$onInvalidating$0(FXUtils.java:42)
	at com.tungsten.fcl.util.FXUtils$$ExternalSyntheticLambda1.invalidated(Unknown Source:2)
	at com.tungsten.fclcore.fakefx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:101)
	at com.tungsten.fclcore.fakefx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:45)
	at com.tungsten.fclcore.fakefx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:70)
	at com.tungsten.fclcore.fakefx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:77)
	at com.tungsten.fclcore.fakefx.beans.property.StringPropertyBase.set(StringPropertyBase.java:111)
	at com.tungsten.fclcore.fakefx.beans.property.StringPropertyBase.set(StringPropertyBase.java:25)
	at com.tungsten.fcl.control.data.ControlButtonData.setText(ControlButtonData.java:55)
	at com.tungsten.fcl.control.view.ControlButton$1.onPositive(ControlButton.java:336)
	at com.tungsten.fcl.control.EditViewDialog.onClick(EditViewDialog.java:106)
	at android.view.View.performClick(View.java:7185)
	at android.view.View.performClickInternal(View.java:7162)
	at android.view.View.access$3500(View.java:819)
	at android.view.View$PerformClick.run(View.java:27678)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ShirosakiMio** [comment]
逝世这个，我这里没法复现
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8119924112
