### ISSUE TITLE
游戏时编辑按键导致启动器崩溃

### ISSUE THREAD

**Issue by PCL1234** [FCL-Team/FoldCraftLauncher#298]
### Launcher Version

1.1.5

### Device Information

HONOR CLK-AN00,Android 13,ARM64

### Problem Description

在游戏时编辑按键并点击"确认"时启动器有概率崩溃

### Java

8

### Renderer

Holy-GL4ES

### Game Version

1.12

### Modifications Made to the Game

Forge

### Launcher Crash Report

Build version: 1.1.5 
Current date: 2024-03-06 16:10:13 
Device: HONOR CLK-AN00 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'void com.tungsten.fclcore.fakefx.beans.InvalidationListener.invalidated(com.tungsten.fclcore.fakefx.beans.Observable)' on a null object reference
	at com.tungsten.fclcore.util.fakefx.ObservableHelper.lambda$invalidate$0$com-tungsten-fclcore-util-fakefx-ObservableHelper(ObservableHelper.java:59)
	at com.tungsten.fclcore.util.fakefx.ObservableHelper$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:811)
	at com.tungsten.fclcore.util.fakefx.ObservableHelper.invalidate(ObservableHelper.java:59)
	at com.tungsten.fcl.control.data.ControlButtonData.invalidate(ControlButtonData.java:140)
	at com.tungsten.fcl.control.data.ControlButtonData.$r8$lambda$H4ug6JzTrWk7HuaSvpnBZxRk2Uw(Unknown Source:0)
	at com.tungsten.fcl.control.data.ControlButtonData$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.tungsten.fcl.util.FXUtils.lambda$onInvalidating$0(FXUtils.java:42)
	at com.tungsten.fcl.util.FXUtils$$ExternalSyntheticLambda1.invalidated(Unknown Source:2)
	at com.tungsten.fclcore.fakefx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:101)
	at com.tungsten.fclcore.fakefx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:45)
	at com.tungsten.fclcore.fakefx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:72)
	at com.tungsten.fclcore.fakefx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:79)
	at com.tungsten.fclcore.fakefx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:113)
	at com.tungsten.fcl.control.data.ControlButtonData.setBaseInfo(ControlButtonData.java:90)
	at com.tungsten.fcl.control.view.ControlButton$1.onPositive(ControlButton.java:337)
	at com.tungsten.fcl.control.EditViewDialog.onClick(EditViewDialog.java:106)
	at android.view.View.performClick(View.java:7738)
	at android.view.View.performClickInternal(View.java:7712)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30495)
	at android.os.Handler.handleCallback(Handler.java:971)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:9205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

### Launcher Log File

[fcl-exported-logs-2024-03-06T16-03-40.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14506751/fcl-exported-logs-2024-03-06T16-03-40.log)

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8155685899
