### ISSUE TITLE
请求更改启动器更新网盘

### ISSUE THREAD

**Issue by DSY-xiaoluo** [FCL-Team/FoldCraftLauncher#314]
> > > > > > 123盘下载需要登录太不好用了！！！ 请换用譬如feijipan.com、pan.huang1111.cn之类的网盘！
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> >>>
> > > > >
> >>>
> > > 
> >>>
> > > >
> >>>>
> > > > > 那至少比百度网盘的64KB/S好吧？
> >>>>
> > > >
> >>>>
> > > >
> >>>
> > > > 
> >>
> > > 
> >>
> > > 
> >>
> > > > 我只能说什么东西都和最差的比，那个东西也是最差的那一档（此评论与FCL启动器无关）
> >>
> > > 
> >>
> > > 
> >>
> >> > 别人爱用什么网盘关你啥事？就只要登录一下你都嫌麻烦？至少不限速吧？那你咋不直接在github里下载呢？
>> 
>> > 
> >
> > >你不觉得麻烦不表示我不觉得麻烦，也不表示其他人都不觉得麻烦，谢谢。而我们知道的是如果不需要登录没有任何人会觉得麻烦。而且同样是不限速不需要登录和需要登录你觉得哪个更好呢？而且有更好的不需要登录的你就非得说要登录的好？现在的这个网盘不需要登录又不限速你还觉得不好？如果启动器里面怎么怎么样都不关我们的事那这个仓库的issue区可以关闭了
> >
> >
> >
> >我还是那句话：别人爱用什么网盘我们就用什么网盘呗，难道人家选择网盘的权利都没有了？偏要听你的抛弃别人常用的网盘而去把所有文件在另一个新的网盘重新上传一次？或者专门为了让我们方便而单独把安装包上传到另一个网盘？别人分享什么资源用了什么网盘还有给你选的权利？
>
>抱歉哈，他们有选择网盘的权利，但是一个东西不好用我们也有提建议的权利。为什么我们有这个权利呢？因为他们的issue区是开着的。我还是那句话如果说一个东西他们爱做成怎么样就做成怎么样那么这个仓库的issue区可以关闭了。开启issue区的目的是为了让我们方便提出建议与汇报bug，如果他们爱怎么样怎么样bug可以全部不修复，建议可以全部不采纳，但是他们没有。你不是这个启动器的开发者，你无权替他们说话。他们愿意接受他人的建议却被你说成了“爱怎么样怎么样”，666
>
>虽然有些建议他们可以拒绝这是他们的权利，但是吧你看这个建议他们拒绝了吗？没有吧，所以他们是像你们说的那样“爱怎么样就怎么样”的人吗？也许是吧

我赞同你的说法，夸克云盘比123云盘还拉，请求更改

_Originally posted by @Deep-Dark-Forest in https://github.com/FCL-Team/FoldCraftLauncher/issues/187#issuecomment-1935411063_

**Comment by zkitefly** [comment]
现在网盘服务商是 

https://github.com/FCL-Team/FoldCraftLauncher/blob/b18134d01d000bcd84608d126ba700c100d2a470/version_map.json#L17

**Comment by DSY-xiaoluo** [comment]
> 现在网盘服务商是，保证很快qwq
> 
> https://github.com/FCL-Team/FoldCraftLauncher/blob/b18134d01d000bcd84608d126ba700c100d2a470/version_map.json#L17

为啥FCL弹窗的网盘更新链接是夸克

**Comment by Deep-Dark-Forest** [comment]
可能是你版本太老了？

**Comment by Deep-Dark-Forest** [comment]
额？我这也是夸克。这是咋回事

**Comment by ShirosakiMio** [comment]
会上github你直接启动器里面更新不就好了

**Comment by zkitefly** [comment]
> > 现在网盘服务商是，保证很快qwq
> > https://github.com/FCL-Team/FoldCraftLauncher/blob/b18134d01d000bcd84608d126ba700c100d2a470/version_map.json#L17
> 
> 为啥FCL弹窗的网盘更新链接是夸克

![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/25c8b7c5-34f0-4923-b106-b4701325bf9b)

你应该点下面的 八蓝米 渠道下载

**Comment by zkitefly** [comment]
@8MiYile 改一下下载页面的描述吧（

**Comment by 8MiYile** [comment]
@zkitefly 你来帮我写markdown 我推上去

**Comment by RRblxminecraftidk** [comment]
Fix needs help crash report Build version: 1.1.5.1 
Current date: 2024-03-20 14:08:22 
Device: Vivo V2102 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.ExceptionInInitializerError
	at com.tungsten.fcl.control.data.ButtonStyles.addStyle(ButtonStyles.java:103)
	at com.tungsten.fcl.control.data.ButtonStyles$$ExternalSyntheticLambda0.accept(Unknown Source:2)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:337)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:295)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.tungsten.fcl.setting.Controllers.getControllersFromDisk(Controllers.java:106)
	at com.tungsten.fcl.setting.Controllers.init(Controllers.java:90)
	at com.tungsten.fcl.setting.Settings.<init>(Settings.java:46)
	at com.tungsten.fcl.setting.Settings.init(Settings.java:39)
	at com.tungsten.fcl.setting.ConfigHolder.init(ConfigHolder.java:74)
	at com.tungsten.fcl.activity.MainActivity.onCreate(MainActivity.java:156)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3908)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8183)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at com.tungsten.fcl.control.data.ButtonStyles.init(ButtonStyles.java:67)
	at com.tungsten.fcl.control.data.ButtonStyles.<clinit>(ButtonStyles.java:58)
	... 31 more

**Comment by Deep-Dark-Forest** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/assets/131975043/ac5de2c2-fc07-4629-8a4e-f1c2d9e09df9

**Comment by 8MiYile** [comment]
啊好好好 石锤力 @ShirosakiMio

**Comment by DSY-xiaoluo** [comment]
> SVID_20240320_183831_1.mp4 
> @zkitefly 现在点击“网盘”按钮时根本就不会跳转到alist.8mi.tech，现在点击“网盘”按钮时会直接跳转到夸克网盘

对，我刚刚试了，还是跳转夸克网盘

**Comment by Deep-Dark-Forest** [comment]
> 会上github你直接启动器里面更新不就好了

不是，现在不是能不能更新的问题，是源代码和实际是否匹配的问题（

**Comment by ShirosakiMio** [comment]
更新文件有两份

**Comment by ShirosakiMio** [comment]
我每天都换新版本上去

**Comment by 8MiYile** [comment]
@ShirosakiMio 他们的意见是 原来的那个网盘可以保留 但同时也要增加第三方或者是八蓝米这个按钮

**Comment by Deep-Dark-Forest** [comment]
> 我每天都换新版本上去

为啥每天都更新？不是每个release更新一次？

**Comment by 8MiYile** [comment]
以及他们在质疑编译的内容是否和源代码一致
@ShirosakiMio

**Comment by zkitefly** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/blob/b18134d01d000bcd84608d126ba700c100d2a470/FCL/src/main/java/com/tungsten/fcl/upgrade/UpdateChecker.java#L22-L23

![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/6bafc559-d5fc-427c-92a0-77f5058d8429)


确实是 updata api 问题

**Comment by ShirosakiMio** [comment]
你猜为什么都能直接收到更新推送

**Comment by 8MiYile** [comment]
他们的意思是 其实可以加个按钮的 因为我那个渠道就是用于国内的 要是仅国外拉取就失去了作用了

**Comment by ShirosakiMio** [comment]
最新都构建到3月20了，我修了些小问题又不推送，直接改更新链接

**Comment by 8MiYile** [comment]
@ShirosakiMio 那我怎么没有在Release上看到你这个推送，我曾经就有说过，我的更新是通过监听github Release来跟随更新

**Comment by ShirosakiMio** [comment]
天天发release闲的蛋疼啊

**Comment by 8MiYile** [comment]
@ShirosakiMio 那你自己留个api 我更改一下 你觉得闲蛋疼就直接留个直链 我直接从直链拉取 或者是通过api也行
