### ISSUE TITLE
Labymod crash

### ISSUE THREAD

**Issue by Rawywy** [FCL-Team/FoldCraftLauncher#355]
when I put laby mod 3 in the forge folder - the game closes ```

```

**Comment by zkitefly** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/issues/266

**Comment by Rawywy** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-04-14 08:41:32
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.class_3304.handler$bej000$dashloader$reloadDash(class_3304.java:1555)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.<init>(class_310.java:652)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at mio.Wrapper.main(Wrapper.java:13)
Caused by: dev.quantumfusion.hyphen.thr.HyphenException: 
Cause: net.minecraft.class_804.<init>(org.joml.Vector3f,org.joml.Vector3f,org.joml.Vector3f,org.joml.Vector3f)Suggestion: Check if the constructor holds all of the fields.

Object Stacktrace:
	in class_804_<@DataNullablenull>
	at field thirdPersonLeftHand in DashModelTransformation_<@DataNullablenull>
	at field transformation in DashBasicBakedModel

Stacktrace:
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:80)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:114)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:39)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:114)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:39)
	at dev.quantumfusion.hyphen.SerializerHandler.scan(SerializerHandler.java:164)
	at dev.quantumfusion.hyphen.SerializerHandler.build(SerializerHandler.java:171)
	at dev.quantumfusion.hyphen.SerializerFactory.build(SerializerFactory.java:181)
	at dev.notalpha.dashloader.io.Serializer.<init>(Serializer.java:31)
	at dev.notalpha.dashloader.io.RegistrySerializer.<init>(RegistrySerializer.java:46)
	at dev.notalpha.dashloader.CacheImpl.<init>(CacheImpl.java:52)
	at dev.notalpha.dashloader.CacheFactoryImpl.build(CacheFactoryImpl.java:74)
	at dev.notalpha.dashloader.client.DashLoaderClient.<clinit>(DashLoaderClient.java:44)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3304.handler$bej000$dashloader$reloadDash(class_3304.java:1555)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.<init>(class_310.java:652)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at mio.Wrapper.main(Wrapper.java:13)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (arm) version Android-10
	Java Version: 17.0.10-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 213422576 bytes (203 MiB) / 463470592 bytes (442 MiB) up to 725614592 bytes (692 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3938.15
	Virtual memory used (MB): 3401.15
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 501.51
	JVM Flags: 3 total; -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar -Xmx692m -Xss1m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		betterfpsdist: Better FPS distance Mod 1.20.1-3.7
		boostedbrightness: Boosted Brightness 2.2.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.97
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.97
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.97
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.97
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.97
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.97
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.97
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.97
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.97
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.97
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.97
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.97
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.97
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.97
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.97
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.97
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chat_heads: Chat Heads 0.10.19
		collective: Collective 6.65
		colormeoutlines: Color Me Outlines 1.1.2
		continuity: Continuity 3.0.0-beta.2+1.20
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
				mm: Manningham Mills 2.3
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		crystaloptimizer: CrystalOptimizer 1.0.0
		dark-loading-screen: Dark Loading Screen 1.6.14
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4
			gbfabrictools: GBfabrictools 1.3.5+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		exordium: Exordium 1.1.3.1-mc1.20.1
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		ferritecore: FerriteCore 6.0.0
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1
		freecam: Freecam 1.1.10+1.20
		healthindicators: PlayerHealthIndicators 1.1.0
		ias: In-Game Account Switcher 8.0.2
		indium: Indium 1.0.21+mc1.20.1
		inventoryhud: Inventory HUD + 3.4.18
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.2
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 7.2.1
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		nohurtcamplus: NoHurtCam+ 2.3.1-1.20.1
		offlineskins: OfflineSkins 1.20.1-v1a-fabric
		reeses-sodium-options: Reese's Sodium Options 1.6.3+mc1.20.1-build.92
		shulkerboxtooltip: Shulker Box Tooltip 4.0.2+1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spark: spark 1.10.53
		starlight: Starlight 1.1.2+fabric.dbc156f
		ukulib: ukulib 1.0.0-beta.3+1.20.1
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		vmp: Very Many Players 0.2.0+beta.7.100
		xaerobetterpvp: Better PVP Mod 23.4.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.3+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off) (fallback)
	NEC status: No NEC detected
	Flywheel Backend: Uninitialized
	Launched Version: 1.20.1 fab
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: ANGLE (Imagination Technologies, Vulkan 1.1.100 (PowerVR Rogue GE8320 (0x22104018)), PowerVR Rogue Vulkan Driver-1.300.2589) GL version 4.6.0 (ANGLE 2.1.1 git hash: b79b72b53460), Google Inc. (Imagination Technologies)
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.' x 6
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

**Comment by DeliciousBread481** [comment]
**dashloader** cant run together with any mods which include **portinglib**
(maybe because some minecraft field got its obfuscated name changed)
