### ISSUE TITLE
Could not connect to servers with ipv6 addresses

### ISSUE THREAD

**Issue by 4li77l3n00b** [FCL-Team/FoldCraftLauncher#360]
### Launcher Version

latest

### Device Information

MatePad Pro 13.2

### Problem Description

IPv4 addresses are tested pingable

### Java

Auto

### Renderer

Holy

### Game Version

1.20.1

### Modifications Made to the Game

Forge

### Launcher Log File

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/15179738/latest_game.log)

**Comment by Chinahfh** [comment]
me,too
我也遇到过

**Comment by nexplorer-3e** [comment]
不清楚是否是 jdk patch 的实现有问题，丢个 mc 日志片段在这
```java
21:46:18] [Render thread/INFO]: Connecting to 240e::1, 25565
[21:46:19] [Server Connector #1/ERROR]: Couldn't connect to server
java.nio.channels.UnsupportedAddressTypeException: null
	at sun.nio.ch.Net.checkAddress(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.checkRemote(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:91) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:88) ~[netty-common-4.1.82.Final.jar:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:88) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:248) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[21:46:19] [Server Connector #1/ERROR]: Caught previously unhandled exception :
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.lang.Exception.getMessage()" is null
	at net.minecraft.class_412$1.run(class_412.java:128) 
```
