### ISSUE TITLE
Please help, (continous crash)

### ISSUE THREAD

**Issue by anoni111** [FCL-Team/FoldCraftLauncher#408]
### Launcher Version

Latest

### Device Information

Samsung s9, snapdragon 845, Android 10

### Problem Description

I had a problem installing version 1.19.2 fabric, it closed suddenly and did not open again, it gave an error, it occurred to me to delete the cache and data to start everything again but every time I install the jre and java libraries at the beginning It crashes and never opens, any solution? Please send capture

Tuve un problema instalando la versión 1.19.2 fabric, se cerró repentinamente y ya no abrió más, ponía error, se me ocurrió borrarle el cache y los datos para así empezar de nuevo todo pero siempre que instalo las librerías jre y los java al principio crashea y nunca abre, alguna solución? Por favor, mando captura

![Screenshot_20240613-162625_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/26054059/1b5f5078-cf44-4500-91b6-ed7ca09adfa3)

### Java

No idea

### Renderer

No idea 

### Game Version

All versions

### Modifications Made to the Game

Fabric, and all versions

### Game Crash Report

Build version: 1.1.6.1 
Current date: 2024-06-13 16:32:41 
Device: Samsung SM-G960U 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.fcl/com.tungsten.fcl.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at com.tungsten.fcl.control.data.ButtonStyles.init(ButtonStyles.java:66)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:337)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:295)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.tungsten.fcl.setting.Controllers.getControllersFromDisk(Controllers.java:109)
	at com.tungsten.fcl.setting.Controllers.init(Controllers.java:93)
	at com.tungsten.fcl.setting.Settings.<init>(Settings.java:46)
	at com.tungsten.fcl.setting.Settings.init(Settings.java:39)
	at com.tungsten.fcl.setting.ConfigHolder.init(ConfigHolder.java:74)
	at com.tungsten.fcl.activity.MainActivity.onCreate(MainActivity.java:156)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	... 11 more

### Launcher Crash Report

Build version: 1.1.6.1 
Current date: 2024-06-13 16:32:41 
Device: Samsung SM-G960U 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.fcl/com.tungsten.fcl.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at com.tungsten.fcl.control.data.ButtonStyles.init(ButtonStyles.java:66)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:337)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:295)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.tungsten.fcl.setting.Controllers.getControllersFromDisk(Controllers.java:109)
	at com.tungsten.fcl.setting.Controllers.init(Controllers.java:93)
	at com.tungsten.fcl.setting.Settings.<init>(Settings.java:46)
	at com.tungsten.fcl.setting.Settings.init(Settings.java:39)
	at com.tungsten.fcl.setting.ConfigHolder.init(ConfigHolder.java:74)
	at com.tungsten.fcl.activity.MainActivity.onCreate(MainActivity.java:156)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	... 11 more

**Comment by ShirosakiMio** [comment]
you can try to delete "FCL/control" folder

**Comment by anoni111** [comment]
> you can try to delete "FCL/control" folder

Thanks bro, that work for me!
