### ISSUE TITLE
Fold craft launcher unresolvable error

### ISSUE THREAD

**Issue by Rahabera** [FCL-Team/FoldCraftLauncher#422]
### Launcher Version

1.1.6.2

### Device Information

Vivo v20,android 11,arm 64

### Problem Description

cannot open fold craft launcher he said unsolvable error

### Java

Java 8

### Renderer

Virgl

### Game Version

1.12.2

### Modifications Made to the Game

Optifine HD U E3

### Launcher Crash Report

Build version: 1.1.6.2 
Current date: 2024-06-26 15:26:44 
Device: Vivo V2043 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.fcl/com.tungsten.fcl.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3757)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3915)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8220)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at com.tungsten.fcl.control.data.ButtonStyles.init(ButtonStyles.java:66)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:337)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:295)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.tungsten.fcl.setting.Controllers.getControllersFromDisk(Controllers.java:109)
	at com.tungsten.fcl.setting.Controllers.init(Controllers.java:93)
	at com.tungsten.fcl.setting.Settings.<init>(Settings.java:46)
	at com.tungsten.fcl.setting.Settings.init(Settings.java:39)
	at com.tungsten.fcl.setting.ConfigHolder.init(ConfigHolder.java:74)
	at com.tungsten.fcl.activity.MainActivity.onCreate(MainActivity.java:156)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3730)
	... 11 more

### Launcher Log File

Build version: 1.1.6.2 
Current date: 2024-06-26 15:26:44 
Device: Vivo V2043 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.fcl/com.tungsten.fcl.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3757)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3915)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8220)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
	at com.tungsten.fcl.control.data.ButtonStyles.init(ButtonStyles.java:66)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:337)
	at com.tungsten.fcl.setting.Controller$Serializer.deserialize(Controller.java:295)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.tungsten.fcl.setting.Controllers.getControllersFromDisk(Controllers.java:109)
	at com.tungsten.fcl.setting.Controllers.init(Controllers.java:93)
	at com.tungsten.fcl.setting.Settings.<init>(Settings.java:46)
	at com.tungsten.fcl.setting.Settings.init(Settings.java:39)
	at com.tungsten.fcl.setting.ConfigHolder.init(ConfigHolder.java:74)
	at com.tungsten.fcl.activity.MainActivity.onCreate(MainActivity.java:156)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3730)
	... 11 more

**Comment by WesleyVanNeck** [comment]
Stop opening closing the issue

**Comment by ShirosakiMio** [comment]
删除FCL/control文件夹

**Comment by kishan639** [comment]
Help
