### ISSUE TITLE
Mod and assembly blockfront

### ISSUE THREAD

**Issue by Llerey** [FCL-Team/FoldCraftLauncher#520]
### Launcher Version

1.1.7.5

### Device Information

Redmi note 11S, android 13, arm64

### Problem Description

It is not possible to run the blockfront mod and install the assembly.

### Java

21

### Renderer

Holy

### Game Version

1.21.1

### Modifications Made to the Game

Neoforge, blockfront 

### Game Crash Report

Build version: 1.1.7.5 
Current date: 2024-08-17 16:55:11 
Device: Xiaomi 2201117SY 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalStateException: Unsupported mod loader neoforge
	at com.tungsten.fclcore.mod.modrinth.ModrinthInstallTask.<init>(ModrinthInstallTask.java:82)
	at com.tungsten.fclcore.mod.modrinth.ModrinthModpackProvider$1.getInstallTask(ModrinthModpackProvider.java:64)
	at com.tungsten.fcl.game.ModpackHelper.getInstallTask(ModpackHelper.java:228)
	at com.tungsten.fcl.ui.download.ModpackInstaller.getModpackInstallTaskAsync(ModpackInstaller.java:174)
	at com.tungsten.fcl.ui.download.ModpackInstaller.getModpackInstallTask(ModpackInstaller.java:116)
	at com.tungsten.fcl.ui.download.ModpackInstaller.getModpackInstallTask(ModpackInstaller.java:108)
	at com.tungsten.fcl.ui.download.LocalModpackPage.onInstall(LocalModpackPage.java:162)
	at com.tungsten.fcl.ui.download.ModpackPage.onClick(ModpackPage.java:75)
	at android.view.View.performClick(View.java:7592)
	at android.view.View.performClickInternal(View.java:7565)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29945)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8348)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by Llerey** [comment]
Mods were installed using modrinch

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10437786857
