### ISSUE TITLE
无法进入游戏主界面

### ISSUE THREAD

**Issue by Dreamwxz** [FCL-Team/FoldCraftLauncher#585]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9 all和v8a版本

### Device Information / 设备信息

xiaomi13pro 安卓14 

### Problem Description / 问题描述

同意协议后无法进入游戏

### Java

无

### Renderer / 渲染器

无

### Game Version / 游戏版本

无

### Modifications Made to the Game / 对游戏所做的修改

无

### Launcher Crash Report / 启动器崩溃报告

Build version: 1.1.7.9 
Current date: 2024-09-13 14:10:33 
Device: Xiaomi 2210132C 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. Expected: main Calling: ForkJoinPool.commonPool-worker-1
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10984)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2441)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:27909)
	at android.widget.ScrollView.requestLayout(ScrollView.java:1744)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.requestLayout(View.java:27909)
	at android.view.View.setBackgroundDrawable(View.java:26190)
	at androidx.appcompat.widget.AppCompatImageView.setBackgroundDrawable(AppCompatImageView.java:148)
	at com.tungsten.fcl.fragment.RuntimeFragment.refreshDrawables(RuntimeFragment.kt:86)
	at com.tungsten.fcl.fragment.RuntimeFragment.onCreateView$lambda$0(RuntimeFragment.kt:44)
	at com.tungsten.fcl.fragment.RuntimeFragment.$r8$lambda$GHJ3iBhJytjfKTgZMaSDCuGh6Oc(Unknown Source:0)
	at com.tungsten.fcl.fragment.RuntimeFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1400)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by ShirosakiMio** [comment]
try this https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10844326154

**Comment by Dreamwxz** [comment]
> 试试这个 https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10844326154

已解决，感谢
