### ISSUE TITLE
PCL在Xiaomi 14 Ultra上无法启动

### ISSUE THREAD

**Issue by merlin-kitsune** [FCL-Team/FoldCraftLauncher#586]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9

### Device Information / 设备信息

Xiaomi 14 Ultra Android 14

### Problem Description / 问题描述

Build version: 1.1.7.9 
Current date: 2024-09-14 09:39:37 
Device: Xiaomi 24031PN0DC 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. Expected: main Calling: ForkJoinPool.commonPool-worker-1
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11065)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2463)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:27972)
	at android.widget.ScrollView.requestLayout(ScrollView.java:1744)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.requestLayout(View.java:27972)
	at android.view.View.setBackgroundDrawable(View.java:26253)
	at androidx.appcompat.widget.AppCompatImageView.setBackgroundDrawable(AppCompatImageView.java:148)
	at com.tungsten.fcl.fragment.RuntimeFragment.refreshDrawables(RuntimeFragment.kt:87)
	at com.tungsten.fcl.fragment.RuntimeFragment.onCreateView$lambda$0(RuntimeFragment.kt:44)
	at com.tungsten.fcl.fragment.RuntimeFragment.$r8$lambda$GHJ3iBhJytjfKTgZMaSDCuGh6Oc(Unknown Source:0)
	at com.tungsten.fcl.fragment.RuntimeFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1400)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by ShirosakiMio** [comment]
用这个
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10844326154
