### ISSUE TITLE
打开启动器概率发生崩溃

### ISSUE THREAD

**Issue by block13566** [FCL-Team/FoldCraftLauncher#590]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [x] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9

### Device Information / 设备信息

MI 9, Android 11(MIUI 12.5),arm64

### Problem Description / 问题描述

打开启动器或游戏崩溃退出返回启动器主界面时有概率发生APP自身崩溃

### Java

无关

### Renderer / 渲染器

无关

### Game Version / 游戏版本

无关

### Modifications Made to the Game / 对游戏所做的修改

无关

### Launcher Crash Report / 启动器崩溃报告

Build version: 1.1.7.9 
Current date: 2024-09-15 20:25:30 
Device: Xiaomi MI 9 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9166)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1708)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:25757)
	at android.widget.ScrollView.requestLayout(ScrollView.java:1641)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.setBackgroundDrawable(View.java:24035)
	at androidx.appcompat.widget.AppCompatImageView.setBackgroundDrawable(AppCompatImageView.java:148)
	at com.tungsten.fcl.fragment.RuntimeFragment.refreshDrawables(RuntimeFragment.kt:87)
	at com.tungsten.fcl.fragment.RuntimeFragment.onCreateView$lambda$0(RuntimeFragment.kt:44)
	at com.tungsten.fcl.fragment.RuntimeFragment.$r8$lambda$GHJ3iBhJytjfKTgZMaSDCuGh6Oc(Unknown Source:0)
	at com.tungsten.fcl.fragment.RuntimeFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1411)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by block13566** [comment]
上面是游戏崩溃时产生的启动器崩溃
这个是打开启动器时发生的崩溃

`Build version: 1.1.7.9 
Current date: 2024-09-15 22:51:10 
Device: Xiaomi MI 9 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9166)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1708)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
	at android.view.View.requestLayout(View.java:25757)
	at android.widget.ScrollView.requestLayout(ScrollView.java:1641)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.setBackgroundDrawable(View.java:24035)
	at androidx.appcompat.widget.AppCompatImageView.setBackgroundDrawable(AppCompatImageView.java:148)
	at com.tungsten.fcl.fragment.RuntimeFragment.refreshDrawables(RuntimeFragment.kt:86)
	at com.tungsten.fcl.fragment.RuntimeFragment.onCreateView$lambda$0(RuntimeFragment.kt:44)
	at com.tungsten.fcl.fragment.RuntimeFragment.$r8$lambda$GHJ3iBhJytjfKTgZMaSDCuGh6Oc(Unknown Source:0)
	at com.tungsten.fcl.fragment.RuntimeFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1411)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10844326154
