### ISSUE TITLE
[Bug] 滚动条操作有偏移

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FCL-Team/FoldCraftLauncher#605]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

593e87f979810c3d3d3f89d48e4b9b04417e699b

### Device Information / 设备信息

HUAWEI P30 Pro HarmonyOS 2.0 (Android 10), arm64

### Problem Description / 问题描述

进入游戏，点开一个有滚动条的页面
触摸模式下，触摸滚动条没有效果
触控板模式下，用鼠标左键（x）触摸滚动条没有效果

### Java

Java 21

### Renderer / 渲染器

Holy-GL4ES

### Game Version / 游戏版本

1.21.1-Fabric

### Modifications Made to the Game / 对游戏所做的修改

Fabric

### Game Crash Report / 游戏崩溃报告

游戏日志
```
[11:33:59] [Render thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: No window pointer found: 0
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:650)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1044)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.internalWindowSizeChanged(GLFW.java:1099)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.callJV(Native Method)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1091)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:303)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1307)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at mio.Wrapper.main(Wrapper.java:21)
[11:33:59] [Render thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: No window pointer found: 0
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:650)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1044)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.internalWindowSizeChanged(GLFW.java:1099)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.callJV(Native Method)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1091)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:303)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1307)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:33:59] [Render thread/INFO]: [STDERR]: 	at mio.Wrapper.main(Wrapper.java:21)
```

**Comment by EatHatsuneShallots** [comment]
196603d85277c7cf0edcff0dcb5442a2df202573 更新：好吧不是不行，而是有偏移

**Comment by ShirosakiMio** [comment]
右侧菜单自己调偏移

**Comment by EatHatsuneShallots** [comment]
> 右侧菜单自己调偏移

不太好调，而且治标不治本

**Comment by ShirosakiMio** [comment]
治不了本才加的这个功能啊

**Comment by EatHatsuneShallots** [comment]
好像开启了忽略刘海屏就没偏移了
