### ISSUE TITLE
1.21.1fabric需要jdk22

### ISSUE THREAD

**Issue by xiaoluo2333** [FCL-Team/FoldCraftLauncher#671]
这是启动日志
==================== Basic Information ====================
FCL Version: 1.1.8.6
Architecture: arm64
Android SDK: 30
Java Version: 21
Renderer: Holy-GL4ES
Summarize: Application error, unable to launch, exit code = 1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:130
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
==================== Start Minecraft ====================
Device: PD2156
Architecture: arm64
CPU:mt6833
Android SDK: 30
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: POJAV_RENDERER=opengles2
Env: POJAV_NATIVEDIR=/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64
Env: JSP=/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64/libjsph21.so
Env: LIBGL_NOINTOVLHACK=1
Env: FORCE_VSYNC=false
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21
Env: LIBGL_MIPMAP=3
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: FCL_NATIVEDIR=/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64
Env: LD_LIBRARY_PATH=/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64
Env: LIBGL_NOERROR=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre21/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=2408x1080
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx4096m
Java argument: -Xms2048m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/【MultiMC】Maintrav整合包轻量版-1.21.1/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/【MultiMC】Maintrav整合包轻量版-1.21.1/【MultiMC】Maintrav整合包轻量版-1.21.1.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-11
Java argument: -Dorg.lwjgl.opengl.libname=libgl4es_114.so
Java argument: -Dorg.lwjgl.freetype.libname=/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64/libfreetype.so
Java argument: -Dfml.earlyprogresswindow=false
Java argument: -Dglfwstub.windowWidth=2408
Java argument: -Dglfwstub.windowHeight=1080
Java argument: -Dglfwstub.initEgl=false
Java argument: -Dloader.disable_forked_guis=true
Java argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Java argument: -Duser.language=zh
Java argument: -Duser.timezone=Asia/Shanghai
Java argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Java argument: -Dsodium.checks.issue2561=false
Java argument: -Djna.boot.library.path=/data/user/0/com.tungsten.fcl/app_runtime/jna/5.14.0
Java argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/user/0/com.tungsten.fcl/app_runtime/jna:/data/app/~~4R5VXQd2iA04T9curkkDug==/com.tungsten.fcl-1csfNoB1Rm1vmGmaE9Hhjg==/lib/arm64
Java argument: -Djna.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dorg.lwjgl.system.SharedLibraryExtractPath=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dio.netty.native.workdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Java argument: -Dminecraft.launcher.version=1.1.8.6
Java argument: -cp
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/fabric-loader/0.16.5/fabric-loader-0.16.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/data/user/0/com.tungsten.fcl/files/plugins/MioLaunchWrapper.jar:/storage/emulated/0/FCL/.minecraft/versions/【MultiMC】Maintrav整合包轻量版-1.21.1/【MultiMC】Maintrav整合包轻量版-1.21.1.jar
Java argument: --add-exports
Java argument: net.fabricmc.loader.impl.launch.knot/net.fabricmc.loader.impl.launch.knot=ALL-UNNAMED
MainClass: mio.Wrapper
MainClass: net.fabricmc.loader.impl.launch.knot.KnotClient
Minecraft argument: --username
Minecraft argument: xiaoluo114514QAQ
Minecraft argument: --version
Minecraft argument: 【MultiMC】Maintrav整合包轻量版-1.21.1
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/versions/【MultiMC】Maintrav整合包轻量版-1.21.1
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 17
Minecraft argument: --uuid
Minecraft argument: b88485dd6ac04869ba2379753abcd6a4
Minecraft argument: --accessToken
Minecraft argument: ***
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: msa
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 2408
Minecraft argument: --height
Minecraft argument: 1080
Hook success
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:220
Done processing args
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:146
Found JLI lib
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:158
Calling JLI_Launch
[20:44:53] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[20:44:53] [ForkJoinPool-1-worker-4/WARN]: Mod com_github_fallen-breath_conditional-mixin uses the version v0.6.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v0'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:44:54] [main/WARN]: Mod resolution failed
[20:44:54] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inventoryprofilesnext 2.0.4 {depends libipn @ [>=6.0.2 <6.1]}, ROOT_FORCELOAD_SINGLE inventoryprofilesnext 2.0.4]
[20:44:54] [main/INFO]: Reason: [HARD_DEP inventoryprofilesnext 2.0.4 {depends libipn @ [>=6.0.2 <6.1]}, HARD_DEP c2me-opts-natives-math 0.3.0+alpha.0.206+1.21.1 {depends java @ [>=22]}]
[20:44:54] [main/INFO]: Fix: add [add:libipn 6.0.2 ([[6.0.2,6.1)])], remove [], replace []
[20:44:54] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install libipn, any version between 6.0.2 (inclusive) and 6.1 (exclusive).
More details:
	 - Mod 'Inventory Profiles Next' (inventoryprofilesnext) 2.0.4 requires any version between 6.0.2 (inclusive) and 6.1 (exclusive) of libipn, which is missing!
	 - Mod 'Concurrent Chunk Management Engine (Optimizations/Natives Math)' (c2me-opts-natives-math) 0.3.0+alpha.0.206+1.21.1 requires version 22 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
[20:44:54] [main/WARN]: Failed to open the error gui!
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open0(FabricMainWindow.java:94) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open(FabricMainWindow.java:88) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:86) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
Caused by: java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.initGC(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.init(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.<init>(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.JFrame.<init>(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.createUi(FabricMainWindow.java:104) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.lambda$open0$0(FabricMainWindow.java:95) ~[fabric-loader-0.16.5.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source) ~[?:?]
OpenJDK exited with code : 1

其中fabric提供了- Mod 'Concurrent Chunk Management Engine (Optimizations/Natives Math)' (c2me-opts-natives-math) 0.3.0+alpha.0.206+1.21.1 requires version 22 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 21!这个报错，意思是需要jdk22

**Comment by xiaoluo2333** [comment]
我之前在电脑上运行同样的版本同样需要我下载jdk22

**Comment by ZhaoHongCong** [comment]
这应该是c2me要22,而不是fabric要22

**Comment by xiaoluo2333** [comment]
> 这应该是c2me要22,而不是fabric要22

hhh我才看出来，那么该怎么搞呢，进fcl目录导jdk22里边不显示啊，文件替换也不行
