### ISSUE TITLE
不知道为什么突然1.7.10版本 增加任何mod 都会闪退。

### ISSUE THREAD

**Issue by frygttt** [FCL-Team/FoldCraftLauncher#693]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [x] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.7

### Device Information / 设备信息

iQOO Z7x, Android 13, arm64

### Problem Description / 问题描述

奇了怪了之前明明正常的哎呀。

### Java

8

### Renderer / 渲染器

Holy-GL4ES

### Game Version / 游戏版本

1.7.10

### Modifications Made to the Game / 对游戏所做的修改

Forge

### Game Crash Report / 游戏崩溃报告

[latest.log](https://github.com/user-attachments/files/17608121/latest.log)

**Comment by frygttt** [comment]
我真服了。怎么又遇到问题了。

**Comment by RuizeSun** [comment]
“SlashBlade” 模組不兼容，建議刪去或更換模組。  

```
[03:31:54] [Client thread/ERROR]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[03:31:54] [Client thread/ERROR]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	unimixins{0.1.17} [UniMixins] (+unimixins-all-0.1.17.jar) 
	UCH	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-0.1.17.jar) 
	UCH	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-0.1.17.jar) 
	UCH	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-0.1.17.jar) 
	UCH	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-0.1.17.jar) 
	UCH	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-0.1.17.jar) 
	UCH	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-0.1.17.jar) 
	UCH	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-0.1.17.jar) 
	UCH	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-0.1.17.jar) 
	UCE	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (拔刀剑-r87.jar) 
[03:31:54] [Client thread/ERROR]: The following problems were captured during this phase
[03:31:54] [Client thread/ERROR]: Caught exception from flammpfeil.slashblade
java.lang.NoClassDefFoundError: org/lwjgl/util/mapped/CacheUtil
	at mods.flammpfeil.slashblade.ItemRendererBaseWeapon.<init>(ItemRendererBaseWeapon.java:171) ~[ItemRendererBaseWeapon.class:?]
	at mods.flammpfeil.slashblade.InitProxyClient.initializeItemRenderer(InitProxyClient.java:52) ~[InitProxyClient.class:?]
	at mods.flammpfeil.slashblade.SlashBlade.preInit(SlashBlade.java:240) ~[SlashBlade.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_432-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_432-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_432-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_432-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_432-internal]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.mapped.CacheUtil
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_432-internal]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_432-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_432-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_432-internal]
	... 44 more
```

**Comment by frygttt** [comment]
不知道为什么回退到1.1.8.4 不会闪退
