### ISSUE TITLE
鼠标无法直接使用，需要用触控点到游戏里后才可以开始用鼠标，并且滚轮方向与Windows相反

### ISSUE THREAD

**Issue by chenmaheng** [FCL-Team/FoldCraftLauncher#732]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.1

### Device Information / 设备信息

xiaomi pad 6s pro , android15 , arm64

### Problem Description / 问题描述

1.当你使用鼠标点击pojav启动游戏并等待游戏启动后，你将无法使用鼠标，仅能使用触控，只有使用触控进入游戏（3D世界）后才可以使用鼠标，但此时访问游戏GUI便可以使用鼠标，但是我并不清楚这是安卓的问题还是启动器的问题，因为我刚刚更新了启动器和安卓系统（安卓 14－>安卓 15）但是我相信不是整合包的问题，因为他在之前都没有发生过这个bug
2.鼠标滚轮的方向永远是和Windows默认相反，希望可以加一个切换方向的开关

### Java

Java17

### Renderer / 渲染器

Holy－GL4ES

### Game Version / 游戏版本

1.20.2

### Modifications Made to the Game / 对游戏所做的修改

optfine_1.20.2_HD_U_I7_pre1 , fabric

### Launcher Log File / 启动器日志文件

[16:26:31] [com.tungsten.fcl.setting.ConfigHolder.loadGlobalConfig/INFO] Creating an empty global config
[16:26:31] [com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorDownloader.checkUpdate/INFO] Checking update of authlib-injector
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:89)
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/.minecraft]] gets fired
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:89)
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/.minecraft]] gets fired
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/.minecraft], version=Version [id=MMC 3.1]] gets fired
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[MMC 3.1], baseDirectory=/storage/emulated/0/.minecraft]] gets fired
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[MMC 3.1], baseDirectory=/storage/emulated/0/.minecraft], version=Version [id=MMC 3.1]] gets fired
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:89)
[16:26:31] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[MMC 3.1], baseDirectory=/storage/emulated/0/.minecraft]] gets fired
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:89)
[16:26:31] [com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.lambda$new$0$com-tungsten-fclcore-auth-yggdrasil-YggdrasilService/INFO] Fetching properties of 81b0b6c8-3a5a-3606-a3e0-35bf3e528e67 from http://main.mrts.fun:20244/api/yggdrasil/
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:134)
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:133)
[16:26:31] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[16:26:33] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[16:26:37] [com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.lambda$new$1/WARNING] Failed to fetch properties of 81b0b6c8-3a5a-3606-a3e0-35bf3e528e67 from http://main.mrts.fun:20244/api/yggdrasil/
com.tungsten.fclcore.auth.ServerDisconnectException: java.io.FileNotFoundException: http://main.mrts.fun:20244/api/yggdrasil/sessionserver/session/minecraft/profile/81b0b6c83a5a3606a3e035bf3e528e67
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.request(YggdrasilService.java:241)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.getCompleteGameProfile(YggdrasilService.java:184)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.lambda$new$0$com-tungsten-fclcore-auth-yggdrasil-YggdrasilService(YggdrasilService.java:67)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at com.tungsten.fclcore.util.fakefx.ObservableCache.lambda$query$0$com-tungsten-fclcore-util-fakefx-ObservableCache(ObservableCache.java:80)
	at com.tungsten.fclcore.util.fakefx.ObservableCache$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: http://main.mrts.fun:20244/api/yggdrasil/sessionserver/session/minecraft/profile/81b0b6c83a5a3606a3e035bf3e528e67
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.tungsten.fclcore.util.io.NetworkUtils.doGet(NetworkUtils.java:199)
	at com.tungsten.fclcore.auth.yggdrasil.YggdrasilService.request(YggdrasilService.java:237)
	... 8 more
[16:26:37] [com.tungsten.fcl.setting.Accounts.lambda$init$8/WARNING] Failed to log AuthlibInjectorAccount [uuid=81b0b6c8-3a5a-3606-a3e0-35bf3e528e67, username=chenmaheng@163.com, server=http://main.mrts.fun:20244/api/yggdrasil/] in
com.tungsten.fclcore.auth.ServerDisconnectException: java.io.FileNotFoundException: http://main.mrts.fun:20244/api/yggdrasil/
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount.lambda$inject$2$com-tungsten-fclcore-auth-authlibinjector-AuthlibInjectorAccount(AuthlibInjectorAccount.java:88)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount$$ExternalSyntheticLambda1.get(Unknown Source:2)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1736)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.FileNotFoundException: http://main.mrts.fun:20244/api/yggdrasil/
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.lambda$getString$0$com-tungsten-fclcore-util-io-HttpRequest$HttpGetRequest(HttpRequest.java:146)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.tungsten.fclcore.util.io.HttpRequest.getStringWithRetry(HttpRequest.java:230)
	at com.tungsten.fclcore.util.io.HttpRequest.access$100(HttpRequest.java:48)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:143)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorServer.refreshMetadata(AuthlibInjectorServer.java:161)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorServer.fetchMetadataResponse(AuthlibInjectorServer.java:155)
	at com.tungsten.fclcore.auth.authlibinjector.AuthlibInjectorAccount.lambda$inject$2$com-tungsten-fclcore-auth-authlibinjector-AuthlibInjectorAccount(AuthlibInjectorAccount.java:86)
	... 8 more
[16:27:06] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$31$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Task failed: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:133)
java.net.SocketTimeoutException: failed to connect to passport.csdn.net/220.185.184.250 (port 443) from /10.10.10.6 (port 44816) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:170)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:148)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.lambda$getString$0$com-tungsten-fclcore-util-io-HttpRequest$HttpGetRequest(HttpRequest.java:145)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.tungsten.fclcore.util.io.HttpRequest.getStringWithRetry(HttpRequest.java:230)
	at com.tungsten.fclcore.util.io.HttpRequest.access$100(HttpRequest.java:48)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:143)
	at com.tungsten.fclcore.util.io.HttpRequest.getJson(HttpRequest.java:103)
	at com.tungsten.fcl.ui.main.MainUI.lambda$checkAnnouncement$2(MainUI.java:133)
	at com.tungsten.fcl.ui.main.MainUI$$ExternalSyntheticLambda4.call(Unknown Source:0)
	at com.tungsten.fclcore.task.Task$SimpleTask.execute(Task.java:1020)
	at com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$22$com-tungsten-fclcore-task-AsyncTaskExecutor(AsyncTaskExecutor.java:243)
	at com.tungsten.fclcore.task.AsyncTaskExecutor$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at com.tungsten.fclcore.util.Lang.lambda$wrap$2(Lang.java:291)
	at com.tungsten.fclcore.util.Lang$$ExternalSyntheticLambda7.run(Unknown Source:2)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1780)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1772)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:27:06] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$31$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Task failed: com.tungsten.fcl.ui.main.MainUI.checkAnnouncement(MainUI.java:134)
java.net.SocketTimeoutException: failed to connect to passport.csdn.net/220.185.184.250 (port 443) from /10.10.10.6 (port 44816) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:170)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:148)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.lambda$getString$0$com-tungsten-fclcore-util-io-HttpRequest$HttpGetRequest(HttpRequest.java:145)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.tungsten.fclcore.util.io.HttpRequest.getStringWithRetry(HttpRequest.java:230)
	at com.tungsten.fclcore.util.io.HttpRequest.access$100(HttpRequest.java:48)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:143)
	at com.tungsten.fclcore.util.io.HttpRequest.getJson(HttpRequest.java:103)
	at com.tungsten.fcl.ui.main.MainUI.lambda$checkAnnouncement$2(MainUI.java:133)
	at com.tungsten.fcl.ui.main.MainUI$$ExternalSyntheticLambda4.call(Unknown Source:0)
	at com.tungsten.fclcore.task.Task$SimpleTask.execute(Task.java:1020)
	at com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$22$com-tungsten-fclcore-task-AsyncTaskExecutor(AsyncTaskExecutor.java:243)
	at com.tungsten.fclcore.task.AsyncTaskExecutor$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at com.tungsten.fclcore.util.Lang.lambda$wrap$2(Lang.java:291)
	at com.tungsten.fclcore.util.Lang$$ExternalSyntheticLambda7.run(Unknown Source:2)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1780)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1772)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:27:06] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$start$1$com-tungsten-fclcore-task-AsyncTaskExecutor/WARNING] An exception occurred in task execution
java.net.SocketTimeoutException: failed to connect to passport.csdn.net/220.185.184.250 (port 443) from /10.10.10.6 (port 44816) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:170)
	at com.tungsten.fclcore.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:148)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.lambda$getString$0$com-tungsten-fclcore-util-io-HttpRequest$HttpGetRequest(HttpRequest.java:145)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.tungsten.fclcore.util.io.HttpRequest.getStringWithRetry(HttpRequest.java:230)
	at com.tungsten.fclcore.util.io.HttpRequest.access$100(HttpRequest.java:48)
	at com.tungsten.fclcore.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:143)
	at com.tungsten.fclcore.util.io.HttpRequest.getJson(HttpRequest.java:103)
	at com.tungsten.fcl.ui.main.MainUI.lambda$checkAnnouncement$2(MainUI.java:133)
	at com.tungsten.fcl.ui.main.MainUI$$ExternalSyntheticLambda4.call(Unknown Source:0)
	at com.tungsten.fclcore.task.Task$SimpleTask.execute(Task.java:1020)
	at com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$22$com-tungsten-fclcore-task-AsyncTaskExecutor(AsyncTaskExecutor.java:243)
	at com.tungsten.fclcore.task.AsyncTaskExecutor$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at com.tungsten.fclcore.util.Lang.lambda$wrap$2(Lang.java:291)
	at com.tungsten.fclcore.util.Lang$$ExternalSyntheticLambda7.run(Unknown Source:2)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1780)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1772)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:39:21] [com.tungsten.fcl.ui.setting.LauncherSettingPage.lambda$onClick$7$com-tungsten-fcl-ui-setting-LauncherSettingPage/INFO] Exporting logs to /storage/emulated/0/FCL/fcl-exported-logs-2024-11-28T16-39-21.log

**Comment by chenmaheng** [comment]
更正一下，是需要一下键盘输入才可以开始用鼠标

**Comment by hd130010** [comment]
提供一下游戏的options.txt文件

**Comment by ShirosakiMio** [comment]
我手机上测试是正常的

**Comment by chenmaheng** [comment]
以下是options.txt

tutorialStep:none
key_key.pickItem:key.mouse.middle
key_key.journeymap.create_waypoint:key.keyboard.b
panoramaScrollSpeed:1.0
chatDelay:0.0
key_key.journeymap.fullscreen.north:key.keyboard.up
chatLinksPrompt:true
operatorItemsTab:true
key_key.playerlist:key.keyboard.tab
textBackgroundOpacity:0.5
useNativeTransport:true
chatScale:1.0
notificationDisplayTime:1.0
key_key.journeymap.fullscreen_waypoints:key.keyboard.n
glintSpeed:0.5
damageTiltStrength:1.0
enableVsync:false
modelPart_cape:true
particles:0
toggleSprint:false
soundDevice:""
mouseSensitivity:0.5
key_key.advancements:key.keyboard.l
advancedItemTooltips:false
key_key.swapOffhand:key.keyboard.f
modelPart_hat:true
entityShadows:false
touchscreen:false
telemetryOptInExtra:false
incompatibleResourcePacks:[]
version:3578
ao:true
mipmapLevels:4
hideMatchedNames:true
key_key.hotbar.5:key.keyboard.5
key_key.hotbar.6:key.keyboard.6
key_key.hotbar.7:key.keyboard.7
key_key.hotbar.8:key.keyboard.8
fullscreen:false
renderDistance:8
key_key.hotbar.1:key.keyboard.1
key_key.hotbar.2:key.keyboard.2
key_key.hotbar.3:key.keyboard.3
discrete_mouse_scroll:false
key_key.hotbar.4:key.keyboard.4
modelPart_left_sleeve:true
soundCategory_record:1.0
key_key.sprint:key.keyboard.left.control
skipRealms32bitWarning:false
key_key.forward:key.keyboard.w
skipMultiplayerWarning:true
key_key.drop:key.keyboard.q
key_key.journeymap.fullscreen_options:key.keyboard.o
prioritizeChunkUpdates:0
narratorHotkey:true
key_key.back:key.keyboard.s
soundCategory_music:0.0
onboardAccessibility:false
toggleCrouch:false
key_key.attack:key.mouse.left
soundCategory_master:1.0
onlyShowSecureChat:false
key_key.use:key.mouse.right
chatWidth:1.0
key_key.saveToolbarActivator:key.keyboard.unknown
chatHeightUnfocused:0.4375
realmsNotifications:true
key_key.journeymap.zoom_in:key.keyboard.equal
showSubtitles:true
showAutosaveIndicator:true
key_key.smoothCamera:key.keyboard.unknown
backgroundForChatOnly:true
chatHeightFocused:1.0
hideServerAddress:false
glDebugVerbosity:1
modelPart_right_pants_leg:true
maxFps:60
renderClouds:"fast"
guiScale:0
forceUnicodeFont:false
hideBundleTutorial:false
biomeBlendRadius:2
key_key.journeymap.zoom_out:key.keyboard.minus
key_key.journeymap.fullscreen.east:key.keyboard.right
simulationDistance:8
entityDistanceScaling:1.0
chatOpacity:1.0
gamma:0.5
key_key.right:key.keyboard.d
key_key.jump:key.keyboard.space
key_key.journeymap.fullscreen.south:key.keyboard.down
resourcePacks:["fabric"]
darknessEffectScale:1.0
modelPart_left_pants_leg:true
chatLineSpacing:0.0
chatColors:true
soundCategory_weather:1.0
mouseWheelSensitivity:1.0
key_key.sneak:key.keyboard.left.shift
modelPart_jacket:true
key_key.spectatorOutlines:key.keyboard.unknown
screenEffectScale:1.0
autoSuggestions:true
highContrast:false
soundCategory_player:1.0
key_key.left:key.keyboard.a
graphicsMode:0
directionalAudio:false
key_of.key.zoom:key.keyboard.c
key_key.journeymap.minimap_type:key.keyboard.left.bracket
mainHand:"right"
lastServer:
allowServerListing:true
overrideHeight:2032
key_key.journeymap.fullscreen_create_waypoint:key.keyboard.b
key_key.journeymap.fullscreen.west:key.keyboard.left
key_key.journeymap.fullscreen_chat_position:key.keyboard.unknown
darkMojangStudiosBackground:false
autoJump:true
chatLinks:true
hideLightningFlashes:false
soundCategory_block:1.0
key_key.journeymap.map_toggle_alt:key.keyboard.j
invertYMouse:false
reducedDebugInfo:false
modelPart_right_sleeve:true
key_key.command:key.keyboard.slash
key_key.screenshot:key.keyboard.f2
fov:0.0
key_key.hotbar.9:key.keyboard.9
soundCategory_neutral:1.0
rawMouseInput:true
key_key.journeymap.minimap_preset:key.keyboard.backslash
attackIndicator:1
key_key.togglePerspective:key.keyboard.f12
soundCategory_ambient:1.0
pauseOnLostFocus:true
lang:zh_cn
key_key.chat:key.keyboard.t
key_key.journeymap.fullscreen.disable_buttons:key.keyboard.h
bobView:true
soundCategory_hostile:1.0
fovEffectScale:1.0
overrideWidth:3048
syncChunkWrites:true
key_key.inventory:key.keyboard.e
key_key.fullscreen:key.keyboard.f11
glintStrength:0.75
key_key.journeymap.minimap_toggle_alt:key.keyboard.period
key_key.loadToolbarActivator:key.keyboard.x
chatVisibility:0
narrator:0
joinedFirstServer:true
key_key.journeymap.toggle_waypoints:key.keyboard.z
soundCategory_voice:1.0
key_key.socialInteractions:key.keyboard.p
