### ISSUE TITLE
Game exited code 1

### ISSUE THREAD

**Issue by Baydy** [FCL-Team/FoldCraftLauncher#82]
### Launcher Version

1.0.6 patch 1

### Device Information

Oppo f9 android 10 arm64

### Problem Description

So I just want to run sodium mod in fabric then I tried making a survival world it made me get out of the game

### Java

Java 17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

Fabric

### Launcher Log File

[20:26:10] [com.tungsten.fcl.setting.ConfigHolder.loadGlobalConfig/INFO] Creating an empty global config
[20:26:10] [com.tungsten.fcl.setting.Accounts.createAuthlibInjectorArtifactProvider/INFO] Using specified authlib-injector: /data/user/0/com.tungsten.fcl/files/plugins/authlib-injector.jar
[20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71)
[20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71)
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 Fabric]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=fabric-loader-0.14.21-1.20.1]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 optifine ]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71)
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 Fabric]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=fabric-loader-0.14.21-1.20.1]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 optifine ]] gets fired
[20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired
[20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71)
[20:26:11] [com.tungsten.fcl.game.TexturesLoader.lambda$textureBinding$11/WARNING] Failed to load texture, using default
java.lang.NullPointerException: Attempt to invoke virtual method 'com.tungsten.fclcore.task.Task com.tungsten.fclcore.auth.offline.Skin.load(java.lang.String)' on a null object reference
	at com.tungsten.fcl.game.TexturesLoader.loadTexture(TexturesLoader.java:101)
	at com.tungsten.fcl.game.TexturesLoader.lambda$textureBinding$11(TexturesLoader.java:274)
	at com.tungsten.fcl.game.TexturesLoader$$ExternalSyntheticLambda3.get(Unknown Source:10)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:11] [com.tungsten.fcl.game.TexturesLoader.lambda$skinBinding$9/WARNING] Failed to load texture offline, using fallback texture
java.lang.NullPointerException: Attempt to invoke virtual method 'com.tungsten.fclcore.task.Task com.tungsten.fclcore.auth.offline.Skin.load(java.lang.String)' on a null object reference
	at com.tungsten.fcl.game.TexturesLoader.loadTexture(TexturesLoader.java:101)
	at com.tungsten.fcl.game.TexturesLoader.lambda$skinBinding$9(TexturesLoader.java:245)
	at com.tungsten.fcl.game.TexturesLoader$$ExternalSyntheticLambda2.get(Unknown Source:6)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:88)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:82)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:79)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:79)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:82)
[20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:88)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:15] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132)
[20:26:15] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133)
[20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.LauncherSettingPage.onClick(LauncherSettingPage.java:204)
[20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53)
[20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.LauncherSettingPage.onClick(LauncherSettingPage.java:204)
[20:26:28] [com.tungsten.fcl.ui.setting.LauncherSettingPage.lambda$onClick$5$com-tungsten-fcl-ui-setting-LauncherSettingPage/INFO] Exporting logs to /storage/emulated/0/FCL/fcl-exported-logs-2023-08-10T20-26-28.log

**Comment by didntpenguin** [comment]
fabric with optifine?

**Comment by zkitefly** [comment]
Try uninstalling OptiFine and try again

**Comment by LegacyGamerHD** [comment]
> ### Launcher Version
> 1.0.6 patch 1
> 
> ### Device Information
> Oppo f9 android 10 arm64
> 
> ### Problem Description
> So I just want to run sodium mod in fabric then I tried making a survival world it made me get out of the game
> 
> ### Java
> Java 17
> 
> ### Renderer
> Holy-GL4ES
> 
> ### Game Version
> 1.20.1
> 
> ### Modifications Made to the Game
> Fabric
> 
> ### Game Crash Report
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> [20:26:10] [com.tungsten.fcl.setting.ConfigHolder.loadGlobalConfig/INFO] Creating an empty global config [20:26:10] [com.tungsten.fcl.setting.Accounts.createAuthlibInjectorArtifactProvider/INFO] Using specified authlib-injector: /data/user/0/com.tungsten.fcl/files/plugins/authlib-injector.jar [20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71) [20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71) [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshingVersionsEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 Fabric]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=fabric-loader-0.14.21-1.20.1]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=null, baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 optifine ]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired [20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71) [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 Fabric]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=fabric-loader-0.14.21-1.20.1]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] LoadedOneVersionEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft], version=Version [id=1.20.1 optifine ]] gets fired [20:26:10] [com.tungsten.fclcore.event.EventBus.fireEvent/INFO] RefreshedVersionsEvent [source=FCLGameRepository [versions=[1.20.1, 1.20.1 Fabric, 1.20.1 optifine , fabric-loader-0.14.21-1.20.1], baseDirectory=/storage/emulated/0/FCL/.minecraft]] gets fired [20:26:10] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fclcore.game.GameRepository.refreshVersionsAsync(GameRepository.java:71) [20:26:11] [com.tungsten.fcl.game.TexturesLoader.lambda$textureBinding$11/WARNING] Failed to load texture, using default java.lang.NullPointerException: Attempt to invoke virtual method 'com.tungsten.fclcore.task.Task com.tungsten.fclcore.auth.offline.Skin.load(java.lang.String)' on a null object reference at com.tungsten.fcl.game.TexturesLoader.loadTexture(TexturesLoader.java:101) at com.tungsten.fcl.game.TexturesLoader.lambda$textureBinding$11(TexturesLoader.java:274) at com.tungsten.fcl.game.TexturesLoader$$ExternalSyntheticLambda3.get(Unknown Source:10) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:11] [com.tungsten.fcl.game.TexturesLoader.lambda$skinBinding$9/WARNING] Failed to load texture offline, using fallback texture java.lang.NullPointerException: Attempt to invoke virtual method 'com.tungsten.fclcore.task.Task com.tungsten.fclcore.auth.offline.Skin.load(java.lang.String)' on a null object reference at com.tungsten.fcl.game.TexturesLoader.loadTexture(TexturesLoader.java:101) at com.tungsten.fcl.game.TexturesLoader.lambda$skinBinding$9(TexturesLoader.java:245) at com.tungsten.fcl.game.TexturesLoader$$ExternalSyntheticLambda2.get(Unknown Source:6) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:88) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:82) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:79) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:79) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:82) [20:26:11] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.HelpPage.refresh(HelpPage.java:88) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:12] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:15] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:132) [20:26:15] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.download.DownloadPage.search(DownloadPage.java:133) [20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.ui.setting.LauncherSettingPage.onClick(LauncherSettingPage.java:204) [20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$19$com-tungsten-fclcore-task-AsyncTaskExecutor/FINE] Executing task: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53) [20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.upgrade.UpdateChecker.check(UpdateChecker.java:53) [20:26:16] [com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$executeNormalTask$29$com-tungsten-fclcore-task-AsyncTaskExecutor/FINER] Task finished: com.tungsten.fcl.ui.setting.LauncherSettingPage.onClick(LauncherSettingPage.java:204) [20:26:28] [com.tungsten.fcl.ui.setting.LauncherSettingPage.lambda$onClick$5$com-tungsten-fcl-ui-setting-LauncherSettingPage/INFO] Exporting logs to /storage/emulated/0/FCL/fcl-exported-logs-2023-08-10T20-26-28.log

remove sodium and its fixed

**Comment by Baydy** [comment]
Thanks
